using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;

namespace ISheetModelLib.Utils
{
    public static class PyCallback
    {
        public static string StringFromDoubleArray(IEnumerable<double> array)
        {
            string result = "";
            for (int i = 0; i < array.Count(); i++)
            {
                result += array.ElementAt(i);
                if (i < array.Count() - 1) result += ",";
            }

            return result;
        }

        public static string StringFromIntArray(IEnumerable<int> array)
        {
            string result = "";
            for (int i = 0; i < array.Count(); i++)
            {
                result += array.ElementAt(i) + ",";
                if (i < array.Count() - 1) result += ",";
            }

            return result;
        }

        public static bool CallScript(string pyExec, string pyFile, string data, string graphType, string outFilename, string showGraphWindow)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            //python interpreter location
            start.FileName = pyExec;

            //argument with file name and input parameters
            start.Arguments = string.Format("{0} {1} {2} {3} {4}", pyFile, data, graphType, outFilename, showGraphWindow);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            //start.LoadUserProfile = true;

            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string errMsg = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    if (errMsg.Length > 0) throw new Exception(errMsg);
                    else return true;
                }
            }
        }
    }
}

